server:
  port: 8761

spring:
  application:
    name: 'discovery'
  profiles:
    active: peer1

eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 90 #default
    leaseRenewalIntervalInSeconds: 30    #default
    metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
        defaultZone: http://peer2:8762/eureka/
